language: d

d:
  - dmd-nightly
  - dmd-beta
  - dmd
  - dmd-2.074.0
  - dmd-2.072.2
  - dmd-2.068.2
  - ldc-beta
  - ldc
  - ldc-1.2.0
  - ldc-0.17.3
  - gdc

matrix:
  allow_failures:
      - d: ldc-beta
      - d: ldc
      - d: ldc-1.2.0
      - d: ldc-0.17.3
      - d: gdc

script:
  - dub test :base
  - dub test :compression
  - dub test :passhash
  - dub test :tls
  - dub test
